### ISSUE TITLE
Style container box and add submenu

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13229]
**THIS ISSUES IS ONLY ABOUT STYLES, just make sure the current actions remains the same and nothings breaks after styling changes**

---------------

As a user I want to be able to add content, widget or form to a container. 

### Code context
This needs to be done in the code we injected into the iframe:
1. CSS code: ```/src/app/portlets/dot-edit-content/shared/iframe-edit-mode.css.ts```
2. HTML code: part comes from the endpoint and part generated in the service ```src/app/portlets/dot-edit-content/services/dot-edit-content-html.service.ts```

### Mock in context:
<img width="559" alt="screen shot 2017-12-17 at 8 14 39 am" src="https://user-images.githubusercontent.com/751424/34080385-61f965ac-e302-11e7-87f7-b800dbe79e7f.png">

### Zeplin:
https://zpl.io/VkK3LBg

**Make sure you check colors, the blue line is not the same as the button**

### SVG icons:
For this buttons lets use svg icons as a ```background-image```, easier to implemente in the iframe context, here is an example of code:

```css
.button-class-example {
    display: block;
    background-color: white;
    background-image: url("data:image/svg+xml;utf8,<svg fill='#000000' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
    background-repeat: no-repeat;
    background-position: 4px;
    width: 32px;
    height: 32px;
    border: none;
    border-radius: 16px;
}

```

#### In this code
1. See that all the attr in the ```<svg>``` tag use single quote
2. You can get the icons from: https://material.io/icons/

### Acceptance Criteria
1. When user click the + button we show a submenu with the options: Content, Widget and Form (hardcoded)
2. Click outside the submenu close the submenu
3. Container box should have a min height of ```120px``` (we need space for user to drop contentlets even when is empty)
4. Button states should be the exact same as the buttons in angular.
5. Match the design
6. Work in all the supported browsers (don't forget IE11 and iPad)
7. Multilanguage
