### ISSUE TITLE
Style contentlet box

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13230]
**THIS ISSUES IS ONLY ABOUT STYLES, just make sure the current actions remains the same and nothings breaks after styling changes**

---------------

As a User I want to be able to edit, move and remove content from a page.

### Code context
This needs to be done in the code we injected into the iframe:
1. CSS code: ```/src/app/portlets/dot-edit-content/shared/iframe-edit-mode.css.ts```
2. HTML code: part comes from the endpoint and part generated in the service ```src/app/portlets/dot-edit-content/services/dot-edit-content-html.service.ts```

### Mock in context
<img width="596" alt="screen shot 2017-12-17 at 8 44 33 am" src="https://user-images.githubusercontent.com/751424/34080600-8aab5f1a-e306-11e7-967c-0c24200c8c15.png">

### Zeplin
1. Normal: https://zpl.io/aBweYwQ
2. Hover: https://zpl.io/bWQPDQ7

### States contentlet box
1. Normal state will have the diagonal blue pattern lines opacity in 40% and NO buttons
2. Hover state will have the diagonal blue pattern lines opacity in 100% and three buttons: drag, edit and remove
3. From normal to hover: we fade in the diagonal blue pattern lines from opacity 40 to 100% and the buttons opacity from 0 to 100%
4. From hover to normal: we fade the elements the other way around.

### Diagonal lines pattern:

```css
.class {
  
  background:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAYAAADgkQYQAAAAPElEQVQoU2NkIACCD/38z4hPDUjBWjt2RpyKYApAhmBVhKwAqyJ0BRiKsClAUYRLAVwRPgVgRYQUgBQBADhDIxfuwmYjAAAAAElFTkSuQmCC")
}
```

Code generated with http://www.patternify.com/

### SVG icons:
For this buttons lets use svg icons as a ```background-image```, easier to implemente in the iframe context, here is an example of code:

```css
.button-class-example {
    display: block;
    background-color: white;
    background-image: url("data:image/svg+xml;utf8,<svg fill='#000000' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
    background-repeat: no-repeat;
    background-position: 4px;
    width: 32px;
    height: 32px;
    border: none;
    border-radius: 16px;
}

```

#### In this code
1. See that all the attr in the ```<svg>``` tag use single quote
2. You can get the icons from: https://material.io/icons/

### Acceptance Criteria

1. When user hover the contentlet box we fade in the buttons and increase opacity in the diagonal lines
2. When user mouse out the contentlet box we restore the "normal" state by animating the opacity of the elements.
3. The drag button should have ```cursor: move```
4. Button states should be the exact same as the buttons in angular
5. Match the design
6. Work in all the supported browsers (don't forget IE11 and iPad)
7. Multilanguage
8. Unit test
