### ISSUE TITLE
External elasticsearch cluster works with community license

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#14309]
Version: 5.0-nightly-2018-04-30_22-12

When using an external ES config with Community license, it correctly connects to the external ES cluster.  Expected behavior with Community is that it only allows embedded ES, non-clustered.

`dotcms-config-cluster-ext.properties`:
```
AUTOWIRE_CLUSTER_ES=false
```

`elasticsearch-override.yml`:
```
cluster.name: dotCMSContentIndex

transport:
    host: 172.20.0.4
    tcp.port: 9300
    tcp.connect_timeout: 2s

discovery.zen:
    ping.unicast.hosts: [ "172.20.0.2:9300","172.20.0.3:9300" ]
    minimum_master_nodes: 1
    ping_timeout: 3s
    join_timeout: 6s
    fd:
        ping_timeout: 3s
        ping_interval: 1s
        ping_retries: 3

node:
    data: false
    master: false

path:
    data: /data/local/esdata
    repo: /data/local/essnapshot/snapshots
    logs: /data/local/logs

http:
    enabled: false
    cors.enabled: false
    port: 9200
    host: localhost

indices.query.bool.max_clause_count: 10240
```

![image](https://user-images.githubusercontent.com/3977301/39654930-03266eaa-4fac-11e8-86c6-a0acea7eb080.png)
