### ISSUE TITLE
Create custom docker image for open distro elasticsearch

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16806]
It should be a thin wrapper around their Docker image that can take 1 extra environmental variable that can be used to set the admin users password.

If this variable is set, then when the image is started up for the first time, we follow the doc here :
https://github.com/opendistro/for-elasticsearch-docs/issues/5
and create a new user file that sets the admin password to the hashed value.

If it is not the first startup, then we do not do anything.

I think the way to implement this is to create a shell script that gets copied to the image and gets set as the new entrypoint.

**Comment by wezell** [comment]
This is so when Elasticsearch comes up for the first time, it sets the admin password, which can be specified in a docker-compose.yml file:
```yaml
version: '3.5'

networks:
  es_net:
  db_net:

services:

  dotcms:
    image: dotcms/dotcms:latest
    environment:
      "CMS_HEAP_SIZE": '4g'
      "CMS_JAVA_OPTS": '-XX:+PrintFlagsFinal'
      "PROVIDER_DB_DNSNAME": 'db'
      "ES_ADMIN_PASSWORD": 'sadfadsfdsfdsfadsadsfd'
    depends_on:
      - db
      - es
    volumes:
      - /opt/dotcms/starter/data/shared:/data/shared
      - /opt/dotcms/starter/data/local:/data/local
      - /opt/dotcms/starter/data/starter.zip:/srv/dotserver/tomcat-8.5.32/webapps/ROOT/starter.zip
    networks:
      - db_net
      - es_net

  db:
    image: dotcms/postgres:latest
    volumes:
      - /opt/dotcms/starter/data/pg:/data/pg
    networks:
      - db_net

  es:
    image: dotcms/es-opendistro:latest
       environment:
         "ES_ADMIN_PASSWORD": 'sadfadsfdsfdsfadsadsfd'
    volumes:
      - /opt/dotcms/elasticsearch:/data/elasticsearch
    networks:
      - es_net



```
