### ISSUE TITLE
Apps - Backend: Rest API issues

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18284]
1. **Required params accept null values:** If a yml file contains a required param and its value="null", the application loads the file without errors

2. **Hidden params with default values are displayed when using fallback configuration for a site:**  Using this yml file:

```
key: "google-translate-app-descriptor"
name: "Google Translation"
description: "Google's translation services can be integrated through this set of configurations."
iconUrl: "/google.png"

allowExtraParameters: false

params:
  secret:
    hidden: true
    type: "STRING"
    label: "label"
    hint: "hint"
    required: true
    value: "My Secret"
```

then I run `GET http://localhost:8080/api/v1/apps/google-translate-app-descriptor/SYSTEM_HOST` , the value is not show with ****

3. **NPE when non-required params are not sent to configure secrets for a site:** 

Using this yml file: 

```
key: "google-translate-app-descriptor"
name: "Google Translation"
description: "Google's translation services can be integrated through this set of configurations."
iconUrl: "/google.png"

allowExtraParameters: false

params:
  secret:
    hidden: true
    type: "STRING"
    label: "label"
    hint: "hint"
    required: true
    value: "null"
  param2:
    hidden: false
    type: "STRING"
    label: "label"
    hint: "hint"
    required: false
  hiddenParam:
    hidden: true
    type: "BOOL"
    label: "label"
    hint: "hint"
    required: false
  extra1:
    hidden: true
    type: "STRING"
    label: "Nolly label"
    hint: "Nolly hint"
    required: false
```

If I configure the site using: 
`POST http://localhost:8080/api/v1/apps/google-translate-app-descriptor/48190c8c-42c4-46af-8d1a-0cd5db894797`

```
{ 
      "secret": {
         "value": "TEST"
      }, 
      "param2": {
         "value": "Nolly"
      }
}
```

this exception is thrown: https://gist.github.com/nollymar/b5c25316decd6f9c2ac9335e7b233af3

4. There is no way to only flush Apps Cache from Maintenance -> Cache. There should be an option on the select box called "Apps Cache" 

5. If I set a custom absolute path to store my yml files, using `APPS_DIR_PATH_KEY` property, the path is ignored and the default `/assets/server/apps/` is used instead

6. It is not possible to edit my secrets for a particular configuration when this yml is used: 
```
key: "nolly-app-descriptor"
name: "Nolly Test"
description: "Nolly test service"
iconUrl: "./teacher.png"

allowExtraParameters: false

params:
  hiddenParam:
    value: true
    hidden: true
    type: "BOOL"
    label: "Hidden"
    hint: "Hidden field hint"
    required: true
  secret:
    value: "v345tiugjeweklrgqherkghfqre998872r11"
    hidden: false
    type: "STRING"
    label: "Secret"
    hint: "hint"
    required: true
  param2:
    value: "v2"
    hidden: false
    type: "STRING"
    label: "Param 2"
    hint: "hint"
    required: true
  NewField:
    value: ""
    hidden: false
    type: "STRING"
    label: "New Field"
    hint: "Type something"
    required: true

```
7. The checkbox param is shown as a text field with **** when I uncheck it, click on save and reopen the configuration again. I'm using this yml file: 

```
key: "google-translate-app-descriptor"
name: "Google Translation"
description: "Google's translation services can be integrated through this set of configurations."
iconUrl: "/google.png"

allowExtraParameters: false

params:
  secret:
    value: "v345tiugjeweklrgqherkghfqre998872r11"
    hidden: false
    type: "STRING"
    label: "label"
    hint: "hint"
    required: true
  param2:
    value: "v2"
    hidden: false
    type: "STRING"
    label: "label"
    hint: "hint"
    required: true
  hiddenParam:
    value: "true"
    hidden: true
    type: "BOOL"
    label: "label"
    hint: "hint"
    required: true
```
