### ISSUE TITLE
Apps: Duplicate params in yml files are not validated

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18416]
It is possible to add a yml file with duplicate params without getting any error or warning in logs. For example: in the following yml file the last 2 fields are exactly the same 

```
key: "nolly-app-descriptor"
name: "Nolly Test"
description: "Nolly test service"
iconUrl: "teacher.png"

allowExtraParameters: false

params:
  hiddenParam:
    value: true
    hidden: false
    type: "BOOL"
    label: "Hidden"
    hint: "Hidden field hint"
    required: true
  secret:
    value: "v345tiugjeweklrgqherkghfqre998872r11"
    hidden: false
    type: "STRING"
    label: "Secret"
    hint: "hint"
    required: true
  param2:
    value: "v2"
    hidden: false
    type: "STRING"
    label: "Param 2"
    hint: "hint"
    required: true
  NewField:
    value: ""
    hidden: false
    type: "STRING"
    label: "New Field"
    hint: "Type something"
    required: false
  NewField:
    value: ""
    hidden: false
    type: "STRING"
    label: "Required"
    hint: "Required"
    required: true
```
