### ISSUE TITLE
Support hazelcast k8 discovery

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18904]
We have customers who are running dotCMS in k8 and want to be able to autowire nodes.  In some k8 environments it just work.  In others, specifically those that are using different network overlay like flannel, hazelcast is unable to perform discovery.  

We need to include the hazelcast-kubernetes discovery jar in our default distro and add the properties to our config that can be used to autowire hazelcast in k8.

**Comment by wezell** [comment]
You need to add:

```
properties>
        <property name="hazelcast.discovery.enabled">true</property>
        <property name="hazelcast.shutdownhook.enabled">false</property> 
    </properties>
```

and 
```
            <discovery-strategies>
                <discovery-strategy enabled="true" class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                  <properties>
                    <property name="namespace">dotcms</property>
                    <property name="service-name">dotcms-headless</property>
                    <property name="service-port">5701</property>
                  </properties>
                </discovery-strategy>

``` 
to the hazel.xml

Additionally, you might need to add the POD_IP to java so hazelcast starts on the correct ip
```
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        - name: CMS_JAVA_OPTS
          value: "-XX:+PrintFlagsFinal -Dhazelcast.local.localAddress=$POD_IP"
```
