### ISSUE TITLE
Increase the base font size

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22165]
**Is your feature request related to a problem? Please describe.**
As a UI designer, I want to increase the base font size to 16px, browser default.

**Describe the solution you'd like**
Set the base font size to the wrapper and use rem for the rest of the elements.

**Describe alternatives you've considered**
N/A

**Additional context**
We need to be responsive here.

**Comment by rjvelazco** [comment]
There is a problem with `rem` because when we use the `block editor` inside `dotCMS`, the `styles` get the base `font size` value of the `iframe`. That's because we're not using `encapsulation`, like `shadowdom`, for the `block editor`.

**Comment by rjvelazco** [comment]
**Problem:** When we use the `block editor` inside `dotCMS` the value of `rem` takes the value of the `root` of the `iframe`.

**Possible solutions:**
1. Use `em` instead of `rem`. Trying this `CSS trick`:

```scss
block-editor {
	font-size: 16px;
	* {
		font-size: inherit;
	}
}
```
2. Create a `sass variable` called `$dot-base-size`, set to `16px` (`$dot-base-size: 16px;`), and use the `sass multiply function` as a substitute for `em`, for example:

```scss
:root {
	$dot-base-size: 16px;
}

.bubble-menu-button {
	with: 2 * $dot-base-size;
}
```

3. Use `Shadow DOM` which can be a bit risky because we need to adjust the implementation inside `dotCMS` and check the `event` handling.


In today's meeting, we agreed that the second solution would be the best one now.
