### ISSUE TITLE
Create an "AI" App

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25593]
From the SOW:

### Purpose:

Hold credentials and options needed to integrate with ChatGPT

### Requirements:

* Create a dotCMS App to collect and store ChatGPT-related data
* The App properties should include:

```
name: "ChatGPT"
description: "Credentials and options for using ChatGPT with dotCMS"
iconUrl: (Point to a copy of the ChatGPT icon)

allowExtraParams: false
params:
  api-key:
    value: ""
    hidden: true
    type: "STRING"
    label: "API Key"
    hint: "Your ChatGPT API key"
    required: true
  role-prompt:
    value: "You are dotCMSbot, and AI assistant to help content creators generate and rewrite content in their content management system."
    hidden: false
    type: "STRING"
    label: "Role Prompt"
    hint: "A prompt describing the role (if any) the chatbot will play for the dotCMS user."
    required: false
```

### Tech:

* Configuration file
    * https://www.dotcms.com/docs/latest/apps-integrations#ConfigFiles

### Testing:

* Verify proper display and operation within dotCMS
* Verify access to App parameters via the plugin \(see 1b, below\)
* dotCMS will perform manual testing on the test environment before sign-off

### Deliverables:

* App configuration file \(see above for contents\)

**Comment by john-thomas-dotcms** [comment]
From the SOW:

## 1a. Create a dotCMS App for ChatGPT

### Purpose:
Hold credentials and options needed to integrate with ChatGPT

### Requirements:
* Create a dotCMS App to collect and store ChatGPT-related data
* The App properties should include:
```
name: "ChatGPT"
description: "Credentials and options for using ChatGPT with dotCMS"
iconUrl: (Point to a copy of the ChatGPT icon)

allowExtraParams: false
params:
  api-key:
    value: ""
    hidden: true
    type: "STRING"
    label: "API Key"
    hint: "Your ChatGPT API key"
    required: true
  role-prompt:
    value: "You are dotCMSbot, and AI assistant to help content creators generate and rewrite content in their content management system."
    hidden: false
    type: "STRING"
    label: "Role Prompt"
    hint: "A prompt describing the role (if any) the chatbot will play for the dotCMS user."
    required: false
```

### Tech:
* Configuration file
    * https://www.dotcms.com/docs/latest/apps-integrations#ConfigFiles

### Testing:
* Verify proper display and operation within dotCMS
* Verify access to App parameters via the plugin (see 1b, below)
* dotCMS will perform manual testing on the test environment before sign-off

### Deliverables:
* App configuration file (see above for contents)
