### ISSUE TITLE
RESEARCH: Evaluate what is required to send from the GHA to the entrypoint.sh

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25821]
### Parent Issue
#24354 

The main idea is understand how a docker container action works and what relevant information we get when pushing files to a repo. 

**Expected result:**
Identify what input will be sent to the action and to the entrypoint.sh. Having this information, define what info will receive the entrypoint.sh and what logic this script will have in order to invoke a "super push" CLI command.

**Comment by fabrizzio-dotCMS** [comment]
As a learning exercise, I built a workflow action + a docker container action aiming to integrate a GitHub repo and our CLI to pull or pull content from a dotCMS instance. 
The repository has the following structure
   repo
     +- .githithub. (Contains the workflow definition)
     +- actions (Our Custom private action)
     +- contents (Represents a customer repo)
     
For every Git push event, the workflow fires the action 
The action is composed of a `yml` definition file, a `Dokerfile` that builds the CLI, and an `entrypoint.sh` script that passes down the parameters and runs the CLI 

in the action yml file we declare and capture the params expected by our cli command

for this particualr excersice I chose to do a Content-Type pull 

The cli command looks like this
 'ct pull FileAsset --workspace /github/workspace/' 

for which the declared params on the action are:

```
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:     
    - ${{ inputs.command }} # match ct
    - ${{ inputs.sub-command }}  # match pull 
    - ${{ inputs.default-action-arg }} # FileAsset
    - ${{ inputs.option }} # --workspace 
    - ${{ inputs.option-value }} # the workspace value
    - ${{ inputs.option-verbose }} # the verbose option
```

Each one entry gets mapped into a param accesible like 
$1, $2, $3 ...  from the entrypoint script 

Then we have the Dockerfile 

- which I used to collect and include all the artifacts required by the cli to work 
- the cli jar itself
- the entrypoint.sh 
- a [run-java script](https://repo1.maven.org/maven2/io/fabric8/run-java-sh/)  which is the defacto script used to launch jars from containerized environments.
- a dot-service.yml which is the place holder for an access token that needs to be injected 
- addiitionally we need to tell the CLI to use the target server (demo in this case)
And we do this overriding the property named 
`dotcms.client.servers.default`Property overriding be accomplished [see](https://es.quarkus.io/guides/config-reference) in this case we do it creating an environment var ENV DOTCMS_CLIENT_SERVERS_DEFAULT=https://demo.dotcms.com/api Notice that The sufix value used to create the environment value must match the name on dot-service.yml file in this case we are using **default**
- and last but not least we need to define another environment variable that will tell the cli where the log-file will live. and that is done like this ```
ENV DOT_CLI_HOME=/dot-cli/
ENV QUARKUS_LOG_FILE_PATH=${DOT_CLI_HOME}dotcms-cli.log
``` 



/dot-cli/

Other findings 
I also tried 


Here's a quick guide I was pointed to to get started with docker container action 
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
