### ISSUE TITLE
Explore JBang features

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26189]
Do some research and evaluate how JBang can help us to provide an easy dotcli installation. 

Here are some links that might be helpful for the research: 

- https://www.jbang.dev/
- https://quarkus.io/get-started/
- https://www.baeldung.com/jbang-guide

**Comment by dcolina** [comment]
After reviewing the functionalities of JBang, we created a demo application (Quarkus CLI application), where we configured the JReleaser plugin to test the entire release process.

This app was created with Picocli and only prints the message "Hello world".

We have configured the JReleaser plugin as follows:

```
# Generated with JReleaser 1.8.0 at 2023-09-05T09:49:01.355976+02:00
project:
  name: qcli-jbang
  description: app -- Sample Quarkus CLI application
  longDescription: app -- Sample Quarkus CLI application
  versionPattern: 'CUSTOM:0Y.0M.MICRO'
  stereotype: CLI
  java:
    mainClass: com.dotcms.GreetingCommand
  copyright: |
    The Apache-2.0 License
  license: Apache-2.0
  links:
    homepage: https://www.dotcms.com
    documentation: https://www.dotcms.com
  authors:
    - dotCMS

release:
  github:
    tagName: 'v{{projectVersion}}'
    releaseName: '{{projectVersion}}'
    overwrite: true
    changelog:
      formatted: ALWAYS
      format: '- {{commitShortHash}} {{commitTitle}}'
      preset: conventional-commits
      contributors:
        format: '- {{contributorName}}'
      hide:
        categories:
          - merge
        contributors:
          - GitHub
          - dependabot

distributions:
  qcli-jbang:
    type: SINGLE_JAR
    active: ALWAYS
    stereotype: CLI
    artifacts:
      - path: target/{{distributionName}}-{{projectVersion}}-runner.jar
        transform: target/{{distributionName}}-{{projectVersion}}.jar

packagers:
  jbang:
    alias: qcli
    active: ALWAYS
    continueOnError: false

```

At this point we must take into account the **packagers** section where the jbang configuration is set, along with the **project.java.mainClass** attribute are the most important for the magic to work. Without this attribute, the release process will fail.

Once we have generated the version, we can install and run the application locally like any other command. The only requirement is to have jbang installed.

Below we can see how the application is installed as command.

```
❯ jbang app install qcli-jbang@dotcms
[jbang] Resolving dependencies...
[jbang]    com.dotcms:qcli-jbang:1.1.0
[jbang] Dependencies resolved
[jbang] Building jar for qcli_jbang.java...
[jbang] Post build with io.quarkus.launcher.JBangIntegration
Oct 24, 2023 11:03:40 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.5.0.Final
Oct 24, 2023 11:03:40 AM io.quarkus.deployment.QuarkusAugmentor run
INFO: Quarkus augmentation completed in 396ms
[jbang] Command installed: qcli-jbang
````

Once installed we can run the application.

```
❯ qcli-jbang
Hello World!
```
