### ISSUE TITLE
Add GHA for Sonar Qube Maven Build

### ISSUE THREAD

**Issue by mbiuki** [dotCMS/core#26993]
### Parent Issue

We are deprecating Gradle builds and so transitioning to full Maven build and we need to create a Sonar Qube workflow for this.

### Task

To create a GHA for this.
A sample is here:

This needs modification - on every pull request branch to run Sonar Qube - adjust accordingly - also adjust for what file paths to scan /dotcms/core, etc.

```
name: Build

on:

  push:

    branches:

      - main

  pull_request:

    types: [opened, synchronize, reopened]

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    permissions: read-all

    steps:

      - uses: actions/checkout@v2

        with:

          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17

        uses: actions/setup-java@v1

        with:

          java-version: 17

      - name: Cache SonarQube packages

        uses: actions/cache@v1

        with:

          path: ~/.sonar/cache

          key: ${{ runner.os }}-sonar

          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages

        uses: actions/cache@v1

        with:

          path: ~/.m2

          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze

        env:

          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=core-maven -Dsonar.projectName='core-maven'
```

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Once unwinded Gradle twist, this is unblock and can have a PR ready to test and review.
