### ISSUE TITLE
[Spike] Find out how to publish a distribution on a NPM packager

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27089]
Publishing a distribution on an NPM (Node Package Manager) packager involves the process of making your software package or library available for others to install and use through the NPM registry. NPM is a package manager for JavaScript, and it is commonly used for managing dependencies and distributing JavaScript code.

The main target is to find the way to publish a distribution through the NPM packager. We have to take in count all the considerations, for instance the commands we need running on the CLI release workflow.

**Comment by dcolina** [comment]
**Publishing on the NPM registry considerations**

1. We must have an account on NPM page.
2. It is necessary to create a PAT to be used on the GHA as a `secret.NPM_TOKEN`.
3. We have to create a manifest file `package.json` as follow:
        ```
        {
            "name": "your-cli-tool",
            "version": "1.0.0",
            "description": "Your CLI Tool",
            "bin": {
                "your-cli-tool": "./bin/your-cli-tool",
                "your-cli-tool-linux": "./bin/your-cli-tool-linux",
                "your-cli-tool-win": "./bin/your-cli-too-win.exe"
            },
           "license": "MIT"
        }
        ```
4. We have to publish our package from a GHA workflow step where we must login into NPM registry previously.
5. Following we describe the workflow steps definition:

```
name: Publish to npm

on:
  workflow_dispatch:

env:
  NODE_VERSION: 19
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public     
```

It is important to be aware you cannot overwrite any version on NPM registry. It's a good practice to use `SemVer` strategy.
