### ISSUE TITLE
ci: Only use cancel-in-progress github workflow option for PRs

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#27659]
Currently our github worklow is set up to cancel a build if a new one is triggered for the same pr or branch.   This works well for a PR when a developer adds a change to their PR it does not clutter up unnecessary builds  or require them to wait for the previous legacy build to finish before the new one can start. 

For other branches though in particular the master branch this can have an unintended side effect.   If we push PRS more frequently that the master build can finish we can end up keep kicking the can and we hardly ever get a build complete by which time we may have many PRs merged which can make it difficult to pick up where an issue may have been introduced.    Builds could be scheduled, but a better way to get I think the required behavior is to keep the concurrency per PR and Branch but to keep the cancel-in-progress option only for PRs.    What effect this has on master branch and others is that if another build run is requested when one is already running it will be marked as pending.   Unlike a full queue though these do not stack so we do not get a backlog of pending builds.   If a new build is requested while one is pending the original pending is canceled are replaced with the new.    This has the impact of building master continuously as fast as it can to completion but not triggering if there is no demand.    This can be done just by making the cancel-in-progress as a conditional.  
```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  # Cancel any in-progress runs for the same branch/PR to prevent delays from changes during build
  # On master and other branches run will set as pending.  Any new builds requested will replace the pending build
  cancel-in-progress: ${{ github.event_name == ‘pull_request’ }}
  ```
