### ISSUE TITLE
Doc: Add a command to init dotCMS with a custom database

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28678]
### Task

After the migration to Maven we lost the ability to deploy a dotCMS instance using a database dump. We should provide a procedure or command that make this process easy for our devs

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

**Comment by dcolina** [comment]
**Note to QA:**

In order to test the external database import the following configuration is required.

```
  dotcms:
    image: dotcms/dotcms:trunk
    environment:
        CMS_JAVA_OPTS: '-Xmx1g '
        LANG: 'C.UTF-8'
        TZ: 'UTC'
        DB_BASE_URL: "jdbc:postgresql://db/dotcms"
        DB_USERNAME: 'dotcmsdbuser'
        DB_PASSWORD: 'password'
        DB_NAME=dotcms
        DB_HOST=db
        DB_LOAD_DUMP_SQL=/path/to/your/dumpfile.sql
        DOT_ES_AUTH_BASIC_PASSWORD: 'admin'
        DOT_ES_ENDPOINTS: 'https://opensearch:9200'
        DOT_INITIAL_ADMIN_PASSWORD: 'admin'
        DOT_DOTCMS_CLUSTER_ID:  'dotcms-production'

    volumes:
      - ./path/to/dumpfile.sql:/path/to/your/dumpfile.sql
```

**Comment by valentinogiardino** [comment]
**IQA PASSED**
Now its possible to init dotCMS with a custom database
[image: dotcms/dotcms:trunk]
```
  dotcms:
    image: dotcms/dotcms:trunk
    environment:
        CMS_JAVA_OPTS: '-Xmx1g '
        LANG: 'C.UTF-8'
        TZ: 'UTC'
        DB_BASE_URL: "jdbc:postgresql://db/dotcms"
        DB_USERNAME: 'dotcmsdbuser'
        DB_PASSWORD: 'password'
        DB_NAME: 'dotcms'
        DB_HOST: 'db'
        DB_LOAD_DUMP_SQL: '/data/dump/dump.sql'
        DOT_ES_AUTH_BASIC_PASSWORD: 'admin'
        DOT_ES_ENDPOINTS: 'https://opensearch:9200'
        DOT_INITIAL_ADMIN_PASSWORD: 'admin'
        DOT_DOTCMS_CLUSTER_ID:  'dotcms-production'
    depends_on:
      - opensearch
      - db
    volumes:
      - cms-shared:/data/shared
      - ./dump-sql/dump.sql:/data/dump/dump.sql
      - ./license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - opensearch-net
    ports:
      - "8080:8080"
      - "8443:8443"
```

<img width="1728" alt="Captura de pantalla 2024-07-09 a la(s) 15 09 20" src="https://github.com/dotCMS/core/assets/77643678/40afa0c9-dcff-4c3b-9967-0d9e799365b9">
<img width="1728" alt="Captura de pantalla 2024-07-09 a la(s) 15 07 53" src="https://github.com/dotCMS/core/assets/77643678/04e10858-e273-4083-aa8f-8eb3e4c27301">
