### ISSUE TITLE
[Spike] Argo ApplicationSet deployment of Helm Chart

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#31387]
### User Story

As a developer I want to investigate how to handle the deployment of individual sandbox environments replacing the current github folder of k8s resources with a reference to a version our helm charts.  We need to also allow for cascading values files enabling a heirarchical customisation including a values file generated from the sandbox provisioner containing references to generated aws resources created for the environment.

This guide is a good example of what we want to customize for our needs the following is a possible example application set to try out.  We can decide how we structure the paths and also how we manage how the initial config file is linked with the terraform resources that will end up generating the {{.name}}-values-generated.yaml file.

https://codefresh.io/blog/helm-values-argocd/

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-my-envs-from-repo-with-version
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/dotCMS/internal-infrastructure.git
      revision: HEAD
      files:
      - path: "path-to-config/**/config.yaml"      
  template:      
    metadata:
      name: '{{.name}}'
    spec:
      # The project the application belongs to.
      project: default
      sources:
        - repoURL: https://dotcms.github.io/helm-charts
          path: charts/dotcms
          targetRevision: '{{.chart}}'
          helm:
            valueFiles:
            - $values/my-values/common-values.yaml          
            - $values/my-values/app-version/{{.version}}-values.yaml              
            - $values/my-values/env-type/{{.environment-type}}-values.yaml  
            - $values/my-values/regions/{{.region}}-values.yaml
            - $values/my-values/envs/{{.name}}-values-generated.yaml
            - $values/my-values/envs/{{.name}}-values.yaml
        - repoURL: 'https://github.com/dotCMS/internal-infrastructure.git'
          targetRevision: HEAD
          ref: values
     
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.name}}'
      {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .prune | default "false" }}
          selfHeal: {{ .selfHeal | default "false" }}
      {{- end }}
```

### Acceptance Criteria

We can demo creating an environment by adding just the required config and values files and the environment can be updated by pushing changes to the values.

This structure will not be created by the provisioner initially and we will rely on external resources already have been created by the provisioner and then removing the generated k8s files and argo app.

Will provide enough information to allow discussion of the structure of the values file hierarchy and how it relates to future promotion of environments.   

Shall provide enough information for us to be able to change the sandbox provisioner to create/update the generated values file instead of the current raw k8s resources.

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://codefresh.io/blog/helm-values-argocd/

### Assumptions & Initiation Needs

Requires ArgoCD to be configured to be able to access the helm-charts private repo initially until it is made public
