### ISSUE TITLE
Create Prototype to add Micrometer Metrics into core

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#32481]
## Description

[Brief description of the issue]

## Acceptance Criteria

- [ ] [Define what needs to be accomplished]

## Additional Notes

[Any additional context or notes]

**Comment by spbolton** [comment]
Some info and best practice on passing tags through to micrometer

For your multi-tenant Kubernetes setup with Micrometer and Prometheus, here are the best practices to ensure consistent tagging between your StatefulSet and application metrics:

## 1. Use Environment Variables for Tag Injection

The most reliable approach is to inject the same tags used in your StatefulSet into your application via environment variables:

```yaml
# StatefulSet configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
  labels:
    app: myapp
    customer: customer-a
    environment: production
    version: "1.2.3"
spec:
  template:
    spec:
      containers:
      - name: myapp
        env:
        - name: CUSTOMER_ID
          value: "customer-a"
        - name: ENVIRONMENT
          value: "production"
        - name: APP_VERSION
          value: "1.2.3"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

## 2. Configure Micrometer Common Tags

In your Spring Boot application, configure common tags that will be applied to all metrics:

```java
@Configuration
public class MicrometerConfig {
    
    @Bean
    public MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> registry.config().commonTags(
            "customer", getEnvOrDefault("CUSTOMER_ID", "unknown"),
            "environment", getEnvOrDefault("ENVIRONMENT", "unknown"),
            "version", getEnvOrDefault("APP_VERSION", "unknown"),
            "pod", getEnvOrDefault("POD_NAME", "unknown"),
            "namespace", getEnvOrDefault("NAMESPACE", "unknown"),
            "replica", extractReplicaFromPodName(getEnvOrDefault("POD_NAME", "unknown"))
        );
    }
    
    private String getEnvOrDefault(String key, String defaultValue) {
        return System.getenv().getOrDefault(key, defaultValue);
    }
    
    private String extractReplicaFromPodName(String podName) {
        // StatefulSet pods follow pattern: <statefulset-name>-<ordinal>
        int lastDash = podName.lastIndexOf('-');
        return lastDash > 0 ? podName.substring(lastDash + 1) : "unknown";
    }
}
```

## 3. Use Kubernetes Downward API for Additional Metadata

Leverage the Downward API to inject more Kubernetes metadata:

```yaml
env:
- name: NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
- name: SERVICE_ACCOUNT
  valueFrom:
    fieldRef:
      fieldPath: spec.serviceAccountName
```

## 4. Implement a Centralized Tagging Strategy

Create a centralized service for managing tags across your application:

```java
@Component
public class MetricsTaggingService {
    
    private final Map<String, String> baseTags;
    
    public MetricsTaggingService() {
        this.baseTags = buildBaseTags();
    }
    
    private Map<String, String> buildBaseTags() {
        Map<String, String> tags = new HashMap<>();
        tags.put("customer", getEnvOrDefault("CUSTOMER_ID", "unknown"));
        tags.put("environment", getEnvOrDefault("ENVIRONMENT", "unknown"));
        tags.put("version", getEnvOrDefault("APP_VERSION", "unknown"));
        tags.put("pod", getEnvOrDefault("POD_NAME", "unknown"));
        tags.put("namespace", getEnvOrDefault("NAMESPACE", "unknown"));
        tags.put("replica", extractReplicaFromPodName(getEnvOrDefault("POD_NAME", "unknown")));
        return Collections.unmodifiableMap(tags);
    }
    
    public Tags getBaseTags() {
        return Tags.of(baseTags.entrySet().stream()
            .map(entry -> Tag.of(entry.getKey(), entry.getValue()))
            .toArray(Tag[]::new));
    }
    
    public Tags withAdditionalTags(String... keyValues) {
        return getBaseTags().and(Tags.of(keyValues));
    }
}
```

## 5. Prometheus Scraping Configuration

Ensure your Prometheus configuration can properly scrape and label metrics:

```yaml
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-metrics
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
  - port: metrics
    path: /actuator/prometheus
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_customer]
      targetLabel: customer
    - sourceLabels: [__meta_kubernetes_pod_label_environment]
      targetLabel: environment
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
```

## 6. Validation and Consistency Checks

Implement validation to ensure tag consistency:

```java
@Component
public class MetricsValidator {
    
    @EventListener
    public void validateTagsOnStartup(ApplicationReadyEvent event) {
        String customerFromEnv = System.getenv("CUSTOMER_ID");
        String environmentFromEnv = System.getenv("ENVIRONMENT");
        
        // Log warnings if critical tags are missing
        if (customerFromEnv == null || customerFromEnv.equals("unknown")) {
            log.warn("Customer ID not properly configured - metrics may be incorrectly tagged");
        }
        
        if (environmentFromEnv == null || environmentFromEnv.equals("unknown")) {
            log.warn("Environment not properly configured - metrics may be incorrectly tagged");
        }
    }
}
```

## Key Benefits of This Approach:

- **Consistency**: Same source of truth for both Kubernetes labels and application metrics
- **Scalability**: Works across multiple customers and environments
- **Maintainability**: Centralized tag management
- **Observability**: Easy to correlate metrics with specific deployments
- **Flexibility**: Can add environment-specific tags without code changes

This approach ensures that your Micrometer metrics will have consistent tagging that matches your StatefulSet labels, making it easier to query and correlate metrics across your multi-tenant environment.
